applications:
- name: hello-world-10
  path: ../build/libs/hello-world-0.0.1-SNAPSHOT.jar
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack.git
  disk_quota: 1G
  instances: 2
  memory: 1G
  routes:
  - route: hello-world-10.cfapps.io
  stack: cflinuxfs3
  services:
    - backend-service
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.0.2_+ }}'
    SPRING_PROFILES_ACTIVE: dev
    test-key: my-new-value
